### ISSUE TITLE
[Bug] Game3 khong di chuyen duoc

### ISSUE THREAD

**Issue by HyuOniichan** [HyuOniichan/J4F_NghienThu#12]
@Chikine 

**Problem**
Loi khong di chuyen duoc 

---
![image](https://github.com/user-attachments/assets/37a1a226-1569-40cd-a972-53f72f4ae095)
---

Khi bam start game, player se tu dong di chuyen sang trai va mac ket o day (?), khong di chuyen duoc nua

**Comment by Chikine** [comment]
@HyuOniichan m bi bel qua nen khong di chuyen duoc day. T de player an giu space = sang phai, tha space = sang trai

**Comment by HyuOniichan** [comment]
@Chikine 
t biet the eo nao duoc =))))))))
clm t tuong la wasd voi arrow key di chuyen, ai nghi toi m dung nut space?

**Comment by HyuOniichan** [comment]
neu ok roi thi m close issue di

**Comment by Chikine** [comment]
> neu ok roi thi m close issue di

ke cai m beo y t fix lai r. pull vao di @HyuOniichan
