### ISSUE TITLE
[Game Idea] water sort

### ISSUE THREAD

**Issue by Chikine** [HyuOniichan/J4F_NghienThu#15]
nhu cai ten...

**Comment by Chikine** [comment]
> @Chikine thoi m loi het dong game trong cai app game offline len day luon di...

@HyuOniichan 
trong day k co co bac...

**Comment by Chikine** [comment]
@HyuOniichan 
![image](https://github.com/user-attachments/assets/a9e140d3-17a1-4bc6-b218-de420e4b25b1) 
Lmao...

**Comment by HyuOniichan** [comment]
@Chikine 
len [ytb](https://www.youtube.com/watch?v=sOtMaF0R5Vc) ma bu code...

**Comment by HyuOniichan** [comment]
@Chikine 

![image](https://github.com/user-attachments/assets/f7279867-883b-4916-a2e3-1a8f9ea49e1c)
ngon roi 
nhung van de la khi t click xong t eo biet la t dang chon binh nao... 

o ma dm m lam duoc het a hay m bu code AI day? Van eo tin m lam duoc...

**Comment by Chikine** [comment]
> @Chikine
> 
> ![image](https://private-user-images.githubusercontent.com/119403471/392047759-f7279867-883b-4916-a2e3-1a8f9ea49e1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNjg5MjIsIm5iZiI6MTczMzI2ODYyMiwicGF0aCI6Ii8xMTk0MDM0NzEvMzkyMDQ3NzU5LWY3Mjc5ODY3LTg4M2ItNDkxNi1hMmUzLTFhOGY5ZWE0OWUxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QyMzMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjRiOWQ1NjI3Yjk3YTdlOGZhM2UyNzhhZmU1ZTQzODNmYzMzZTUwYjY4NmQ4M2Y5OGY2OGY0NDI3YThlNjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AXrFksFPhctVpv2g7kyJle_xLlmcJs-dgp9dm5y-cUY) ngon roi nhung van de la khi t click xong t eo biet la t dang chon binh nao...
> 
> o ma dm m lam duoc het a hay m bu code AI day? Van eo tin m lam duoc...
@HyuOniichan co thang d nao bu code AI ma viet dung 1 file code 200 dong khong... 
Trong cai file t co ghi chu thich cac thu day, ca game 4 voi game 5 la t tu lam het 😎
