### ISSUE TITLE
[Game Idea] ran san moi

### ISSUE THREAD

**Issue by HyuOniichan** [HyuOniichan/J4F_NghienThu#19]
co huong dan full hd khong che!!!
[codelearn](https://codelearn.io/sharing/lam-game-ran-san-moi-bang-javascript)

**Comment by Chikine** [comment]
? Co phai dung canvas k?

**Comment by Chikine** [comment]
@HyuOniichan fr 
![image](https://github.com/user-attachments/assets/65f0d176-45f9-4b54-abd8-40292fb71cbe)

**Comment by HyuOniichan** [comment]
no dung thu vien ma... 
ma sao cung duoc...
